variables:
  GIT_STRATEGY: none

# Tests for Melodic with Install
melodic-catkin_build-install:
  image: mrm-git.e-technik.uni-ulm.de:4567/aduulm/docker_images/aduulm-ros-melodic:latest
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - build_repo_with_dependencies.sh gitlab_install

# Tests for Melodic without install
melodic-catkin_build-no_install:
  image: mrm-git.e-technik.uni-ulm.de:4567/aduulm/docker_images/aduulm-ros-melodic:latest
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - build_repo_with_dependencies.sh gitlab_no_install
